services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fyp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:1234@db:5432/fyp
      SECRET_KEY: change-me
      AI_DIR: /app/ai
      VIDEO_ROOT: /app/ai
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
